### PR TITLE
Wallmounted Disposals

### PR DESCRIPTION
**Pull request by SheepFighter**
image
A fairly trivial PR, this. It ports Goon's wallmounted disposals, thereby saving me no small amount of obsessive distress.
Additionally, it fixes the blasted labor shuttle wall-problem.
Per usual, the stuff in the WIP folder can be safely ignored.
image

### CODE REVIEW

**Comment by taukausanake** [comment]
Damn those things are ugly. Are they too small for people to fit inside of? I don't play Goon so I wouldn't know

**Comment by taukausanake** [comment]
Okay so, something I noticed. This seems to do A LOT more than just the disposal bins. I was wondering why there are 38 changed files. That's because there are other projects in here than just this one.

Upon further notice, you're pushing your master. Which has all your edits in it. This is kind of why branches exist, to keep work isolated

**Comment by SheepFighter** [comment]
As I said, ignore the WIP stuff. I know how branches work, but seeing as the WIP folder exists and that this is an obscure codebase with no more than four people regularly downloading, I didn't think it was necessary to go that trouble.

**Comment by taukausanake** [comment]
It really is, and is not that much trouble if I can do it. I don't want to be anal about it but it's just better practice

**Pull request merged**
